Learning-Fuze/c319_DIYblogging_tracker

- dist/index.html
- package.json
- src/components/app.jsx
- src/components/header.jsx
- src/components/project-card.jsx
- src/components/project-catalog.jsx
- src/index.jsx
, added CDN for bootstrap4 and font awesome,
added app, header, project-card, and project-catalog components
> initial component setup

- server/public/styles.css
- src/components/app.jsx
- src/components/dashboard.jsx
- src/components/header.jsx
- src/components/project-card.jsx
https://www.meistertask.com/app/task/lRZYN9Fj/create-app-html-css-skeleton
> User dashboard skeleton

- server/public/styles.css
- src/components/app.jsx
- src/components/create-project-form.jsx
- src/components/header.jsx
- src/components/hero-panel.jsx
- src/components/project-catalog.jsx
…minor updates to project-catalog, and create-project-form components, added css
> Homepage - hero panel component

- src/components/app.jsx
- src/components/footer.jsx
- src/components/user-signup.jsx
Corrected the Sign up component
> Sign up screen

- server/public/api/signup.php
> signup.php that allows posting new user info

- package-lock.json
- package.json
- server/public/styles.css
- src/components/app.jsx
- src/components/layout/footer.jsx
- src/components/layout/header.jsx
- src/components/layout/hero-panel.jsx
- src/components/layout/layout.css
- src/components/layout/scroll-to-top.jsx
- src/components/profile/dashboard.jsx
- src/components/project/project-card.jsx
- src/components/project/project-details.jsx
- src/index.jsx
npm install react-router-dom,
added scroll-to-top.jsx component,
routed header, footer, signup, login, hero panel, project details, project card,
still need to route create project button, create project form...
> Add react router dom

- server/public/index.html
- src/components/project/timeline-entry-form.jsx
still needs image uploads input handler
> added onChange handler for timeline entry form inputs

- server/public/styles.css
- src/components/project/timeline-entry-form.jsx
- src/components/project/timeline.jsx
since team decided not to refactor to reactstrap, reverted to boostrap4
> reverted modal to bootstrap

- server/public/api/projects.php
- src/components/app.jsx
- src/components/profile/dashboard.jsx
- src/components/project/project-card.jsx
- src/components/project/project-details.jsx
Reverts Learning-Fuze/c319_DIYblogging_tracker#47
> Revert "User logged in conditionals"

- server/public/styles.css
- src/components/layout/modal.jsx
- src/components/project/timeline-entry-form.jsx
- src/components/project/timeline.jsx
added css for modal,
refactored timeline and timeline form to use modal,
added image upload input handlers
> refactored to use new modal.jsx component,

- server/public/api/login.php
- server/public/api/project-details.php
- server/public/api/projects.php
- src/components/app.jsx
- src/components/forms/user-signup.jsx
- src/components/layout/footer.jsx
- src/components/layout/header.jsx
- src/components/layout/modal.jsx
- src/components/profile/dashboard.jsx
- src/components/project/project-details.jsx
updated endpoints to return hard-coded user data, stored userSeshData in state, standardized how the data is used across components, removed console.logs,
fixed spacing and layout of routes on app.jsx
added username to session superglobal in PHP login, project, and project-details files
BUG - while on another users dashboard, click on your user icon, does not render your cards
Postman - https://www.getpostman.com/collections/19b7e96a3b8ffc2d730d
> Refactor to simplify user sesh data flow

- server/public/images/loader.svg
- server/public/styles.css
- src/components/profile/dashboard.jsx
> added loading icon to dashboard page

- server/public/api/projects.php
- src/components/profile/dashboard.jsx
since we already have error handling for no projects in dashboard
> deleted error handling in projects.php 

- server/public/api/guest-login.php
- src/components/app.jsx
- src/components/forms/user-login.jsx
Change John Doe's username to 'Guest' and email to 'guest@guest.guest'
> added a guest button

- server/public/api/project-details.php
- server/public/styles.css
- src/components/forms/forms.css
- src/components/forms/user-login.jsx
- src/components/layout/header.jsx
- src/components/profile/dashboard.jsx
- src/components/project/timeline.jsx
> added timeline description,

- server/public/api/projects.php
- src/components/app.jsx
- src/components/forms/user-login.jsx
- src/components/layout/header.jsx
- src/components/profile/dashboard.jsx
- src/components/project/project-card.jsx
- src/components/project/project-details.jsx
- fixed componentdidupdate
- routing is working with usernames
> Merging jess component update

- src/components/app.jsx
- src/components/forms/create-project-form.jsx
- src/components/forms/user-signup.jsx
- src/components/project/project-catalog.jsx
- src/components/project/timeline-entry-form.jsx
added their checkboxes to form,
fixed the category error handler on the form to not appear until submit attempt,
cleaned up some formatting
> added health and crafting to homepage filter,

- server/public/styles.css
- src/components/layout/header.jsx
- src/components/layout/layout.css
- src/components/profile/dashboard.jsx
- src/components/project/project-card.jsx
- src/components/project/project.css
added methods to handle clicks and mouseLeave and scroll events,
deleted empty profile.css file,
added CSS styling for dropdowns
> refactor header and project card dropdown behavior,

- src/components/forms/create-project-form.jsx
> added error message if project title is longer than 45 characters

- server/public/index.html
- server/public/styles.css
- src/components/forms/user-login.jsx
- src/components/forms/user-signup.jsx
- src/components/layout/header.jsx
- src/components/layout/hero-panel.jsx
- src/components/layout/layout.css
- src/components/project/project-card.jsx
- src/components/project/project-catalog.jsx
- src/components/project/project-details.jsx
- src/components/project/project.css
- src/components/project/timeline-entry.jsx
project card css changes
font size changes
remove username on menu when screen is small
changed our story
> mobile sizing dropdown

- src/components/app.jsx
- src/components/project/project-catalog.jsx
moved state to app.jsx and added method/callback to set state,
added componentDidMount to handle query string in direct URL
> refactored to use query string for filtered views,

- server/public/api/edit/edit-item.php
- server/public/api/edit/edit-project.php
- server/public/api/edit/edit-timeline-entry.php
This has both the changes for editing timeline entries and editing items.
> Edit timeline entry

- server/public/api/edit/edit-project.php
- server/public/images/checkmark.svg
- server/public/styles.css
- src/components/forms/create-project-form.jsx
- src/components/forms/edit-project-form.jsx
- src/components/layout/layout.css
- src/components/project/project-details.jsx
Feature to update project details, name, and image
> Update project connection

- server/public/api/check-login.php
- server/public/styles.css
- src/components/404/404.css
- src/components/404/page-not-found.jsx
- src/components/app.jsx
- src/components/forms/create-project-form.jsx
- src/components/forms/forms.css
- src/components/forms/user-login.jsx
- src/components/forms/user-signup.jsx
- src/components/layout/hero-panel.jsx
- src/components/project/items-used-entry-form.jsx
- src/components/project/project-catalog.jsx
- src/components/project/timeline-entry-form.jsx
- src/hoc/auth.js
- src/hoc/auth.jsx
added 404 component, added prompts for password and image uploads, added auth HOC to redirect to login page for non-logged-in visit to create-project-form, added conditional rendering for hero panel to show guest login option
> Add form prompts and redirects
